apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgclass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageclassifier
  template:
    metadata:
      labels:
        app: imageclassifier
    spec:
      containers:
      - name: cv-app
        image: demokry.azurecr.io/dda-devtest
        ports:
        - containerPort: 8501
