apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgclass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageclassifier
  template:
    metadata:
      labels:
        app: imageclassifier
    spec:
      containers:
      - name: cv-app
        image: gcr.io/mlops-317803/imgwebapp:v1
        ports:
        - containerPort: 8501
